apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-sales
  namespace: crm
spec:
  serviceName: postgres-sales
  replicas: 1
  selector:
    matchLabels:
      app: postgres-sales
  template:
    metadata:
      labels:
        app: postgres-sales
    spec:
      initContainers:
        - name: init-schema
          image: busybox:1.36
          command:
            - /bin/sh
            - -c
            - |
              echo "CREATE SCHEMA IF NOT EXISTS sales;" > /docker-entrypoint-initdb.d/01-schema.sql
              echo "GRANT ALL PRIVILEGES ON SCHEMA sales TO crm;" >> /docker-entrypoint-initdb.d/01-schema.sql
          volumeMounts:
            - name: initdb-scripts
              mountPath: /docker-entrypoint-initdb.d

      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: crm
            - name: POSTGRES_USER
              value: crm
            - name: POSTGRES_PASSWORD
              value: crm
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: initdb-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: initdb-scripts
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-sales
  namespace: crm
spec:
  selector:
    app: postgres-sales
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
