package com.crm.communication.infrastructure.messaging

import com.fasterxml.jackson.annotation.JsonProperty
import java.time.OffsetDateTime

data class DomainEventEnvelope(
    @JsonProperty("eventType") val eventType: String = "",
    @JsonProperty("source") val source: String = "",
    @JsonProperty("actorId") val actorId: String? = null,
    @JsonProperty("payload") val payload: DomainEventPayload = DomainEventPayload(),
)

data class DomainEventPayload(
    @JsonProperty("entityId") val entityId: String? = null,
    @JsonProperty("customerId") val customerId: String? = null,
    @JsonProperty("contactId") val contactId: String? = null,
    @JsonProperty("displayName") val displayName: String? = null,
    @JsonProperty("email") val email: String? = null,
    @JsonProperty("fromStage") val fromStage: String? = null,
    @JsonProperty("toStage") val toStage: String? = null,
    @JsonProperty("changedAt") val changedAt: OffsetDateTime? = null,
    @JsonProperty("deactivatedAt") val deactivatedAt: OffsetDateTime? = null,
    @JsonProperty("registeredAt") val registeredAt: OffsetDateTime? = null,
    @JsonProperty("invoiceId") val invoiceId: String? = null,
    @JsonProperty("subscriptionId") val subscriptionId: String? = null,
    @JsonProperty("totalAmount") val totalAmount: String? = null,
    @JsonProperty("amount") val amount: String? = null,
    @JsonProperty("currency") val currency: String? = null,
    @JsonProperty("dueDate") val dueDate: String? = null,
    @JsonProperty("generatedAt") val generatedAt: OffsetDateTime? = null,
    @JsonProperty("paymentId") val paymentId: String? = null,
    @JsonProperty("reason") val reason: String? = null,
    @JsonProperty("failedAt") val failedAt: OffsetDateTime? = null,
    @JsonProperty("planId") val planId: String? = null,
    @JsonProperty("cancelledAt") val cancelledAt: OffsetDateTime? = null,
    @JsonProperty("ticketId") val ticketId: String? = null,
    @JsonProperty("requesterId") val requesterId: String? = null,
    @JsonProperty("assigneeId") val assigneeId: String? = null,
    @JsonProperty("subject") val ticketSubject: String? = null,
    @JsonProperty("priority") val priority: String? = null,
    @JsonProperty("slaDeadline") val slaDeadline: OffsetDateTime? = null,
    @JsonProperty("breachDurationSeconds") val breachDurationSeconds: Long? = null,
    @JsonProperty("breachedAt") val breachedAt: OffsetDateTime? = null,
    @JsonProperty("score") val score: Int? = null,
    @JsonProperty("submittedAt") val submittedAt: OffsetDateTime? = null,
    @JsonProperty("fromStatus") val fromStatus: String? = null,
    @JsonProperty("toStatus") val toStatus: String? = null,
    @JsonProperty("closedAt") val ticketClosedAt: OffsetDateTime? = null,
    @JsonProperty("reopenedAt") val reopenedAt: OffsetDateTime? = null,
    @JsonProperty("escalatedTo") val escalatedTo: String? = null,
    @JsonProperty("newPriority") val newPriority: String? = null,
    @JsonProperty("escalatedAt") val escalatedAt: OffsetDateTime? = null,
    @JsonProperty("resolution") val resolution: String? = null,
    @JsonProperty("resolvedAt") val resolvedAt: OffsetDateTime? = null,
    @JsonProperty("queueId") val queueId: String? = null,
    @JsonProperty("slaType") val slaType: String? = null,
    @JsonProperty("recoveredAt") val recoveredAt: OffsetDateTime? = null,
    @JsonProperty("surveyDeliveryFailedAt") val surveyDeliveryFailedAt: OffsetDateTime? = null,
    @JsonProperty("campaignId") val campaignId: String? = null,
    @JsonProperty("name") val campaignName: String? = null,
    @JsonProperty("opportunityId") val opportunityId: String? = null,
    @JsonProperty("isWon") val isWon: Boolean? = null,
    @JsonProperty("outcome") val outcome: String? = null,
    @JsonProperty("winLossReasonCategory") val winLossReasonCategory: String? = null,
    @JsonProperty("quoteId") val quoteId: String? = null,
    @JsonProperty("period") val period: String? = null,
    @JsonProperty("projectedRevenue") val projectedRevenue: String? = null,
    @JsonProperty("previousOwnerId") val previousOwnerId: String? = null,
    @JsonProperty("newOwnerId") val newOwnerId: String? = null,
    @JsonProperty("reassignedAt") val reassignedAt: OffsetDateTime? = null,
    @JsonProperty("impressions") val impressions: Long? = null,
    @JsonProperty("clicks") val clicks: Long? = null,
    @JsonProperty("spend") val spend: String? = null,
    @JsonProperty("syncedAt") val syncedAt: OffsetDateTime? = null,
    @JsonProperty("attributedRevenue") val attributedRevenue: String? = null,
    @JsonProperty("attributedAt") val attributedAt: OffsetDateTime? = null,
    @JsonProperty("revenue") val conversionRevenue: String? = null,
    @JsonProperty("occurredAt") val occurredAt: OffsetDateTime? = null,
    @JsonProperty("source") val source: String? = null,
    @JsonProperty("granted") val granted: Boolean? = null,
    @JsonProperty("purpose") val purpose: String? = null,
)
