quarkus.datasource.db-kind=postgresql

mp.messaging.incoming.sales-opportunity-events.connector=smallrye-kafka
mp.messaging.incoming.sales-opportunity-events.topic=crm.sales.opportunity.closed
mp.messaging.incoming.sales-opportunity-events.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.sales-opportunity-events.group.id=marketing-service-test

mp.messaging.incoming.sales-opportunity-events.failure-strategy=dead-letter-queue
mp.messaging.incoming.sales-opportunity-events.dead-letter-queue.topic=crm.sales.opportunity.closed.dlq
mp.messaging.incoming.sales-opportunity-events.dead-letter-queue.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.incoming.sales-opportunity-events.dead-letter-queue.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.incoming.sales-opportunity-events.dead-letter-queue.max-retries=3
mp.messaging.incoming.sales-opportunity-events.dead-letter-queue.delay=1s

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=no-file

quarkus.log.level=INFO
quarkus.log.category."com.crm.marketing".level=DEBUG
