-- ═══════════════════════════════════════════════════════════════════════════
-- Initial schema for the CIAM (Customer Identity & Access Management)
-- bounded context.
--
-- Tables:
--   ciam.customer  — the top-level person or organisation record
--   ciam.contact  — contact details (email, phone) linked to a customer
-- ═══════════════════════════════════════════════════════════════════════════

CREATE SCHEMA IF NOT EXISTS ciam;

-- ═══════════════════════════════════════════════════════════════════════════
-- Customer table
-- ═══════════════════════════════════════════════════════════════════════════
-- The top-level person or organisation record in the CRM.  A customer moves
-- through a lifecycle (LEAD → QUALIFIED → OPPORTUNITY → CUSTOMER → ADVOCATE
-- → CHURNED) modelled by [LifecycleStateMachine].

CREATE TABLE IF NOT EXISTS ciam.customer (
    customer_id     UUID            NOT NULL PRIMARY KEY,
    display_name    VARCHAR(255)    NOT NULL,
    lifecycle_stage VARCHAR(20)     NOT NULL
                    CHECK (lifecycle_stage IN (
                        'LEAD', 'QUALIFIED', 'OPPORTUNITY',
                        'CUSTOMER', 'ADVOCATE', 'CHURNED'
                    )),
    source          VARCHAR(100),
    is_active       BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ     NOT NULL,
    updated_at      TIMESTAMPTZ     NOT NULL
);

COMMENT ON TABLE ciam.customer IS
    'Top-level person or organisation record. Lifecycle stage driven by domain events.';

COMMENT ON COLUMN ciam.customer.source IS
    'Acquisition channel (e.g. "website", "partner", "event"). Free-form for analytics.';

COMMENT ON COLUMN ciam.customer.is_active IS
    'Soft-delete flag. FALSE means the record is logically deleted but retained for audit.';

-- ═══════════════════════════════════════════════════════════════════════════
-- Contact table
-- ═══════════════════════════════════════════════════════════════════════════
-- Contact details (email, phone, title) linked to a customer aggregate root.
-- Email and phone are stored as embedded columns (JPA @Embedded) flattened
-- into the contact table: email_value / email_is_primary / email_is_verified
-- and phone_value / phone_country_code / phone_type.

CREATE TABLE IF NOT EXISTS ciam.contact (
    contact_id          UUID            NOT NULL PRIMARY KEY,
    customer_id         UUID            NOT NULL
                        REFERENCES ciam.customer(customer_id) ON DELETE CASCADE,
    first_name          VARCHAR(100)    NOT NULL,
    last_name           VARCHAR(100)    NOT NULL,
    title               VARCHAR(100),
    email_value         VARCHAR(255)    NOT NULL,
    email_is_primary    BOOLEAN,
    email_is_verified   BOOLEAN,
    phone_value         VARCHAR(30),
    phone_country_code  VARCHAR(5),
    phone_type          VARCHAR(10)
                        CHECK (phone_type IN ('MOBILE', 'LANDLINE', 'OTHER')),
    created_at          TIMESTAMPTZ     NOT NULL
);

COMMENT ON TABLE ciam.contact IS
    'Contact details (email / phone) for a customer. Embedded JPA value objects flattened into columns.';

COMMENT ON COLUMN ciam.contact.title IS
    'Job title or role (e.g. "CTO", "Head of Procurement").';

COMMENT ON COLUMN ciam.contact.email_value IS
    'Primary email address. Part of EmailAddressEmbeddable.';

COMMENT ON COLUMN ciam.contact.phone_type IS
    'Phone type discriminator: MOBILE, LANDLINE, or OTHER. Part of PhoneNumberEmbeddable.';

-- Foreign-key index: speeds up the common "find all contacts for a customer"
-- query generated by CustomerRepository and the JPA @ManyToOne relationship.
CREATE INDEX IF NOT EXISTS ix_contact_customer_id
    ON ciam.contact (customer_id);
