apiVersion: v1
kind: Service
metadata:
  name: ciam-service-nodeport
  namespace: crm
spec:
  selector:
    app: ciam-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: sales-service-nodeport
  namespace: crm
spec:
  selector:
    app: sales-service
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: billing-service-nodeport
  namespace: crm
spec:
  selector:
    app: billing-service
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30083
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: support-service-nodeport
  namespace: crm
spec:
  selector:
    app: support-service
  ports:
    - port: 8084
      targetPort: 8084
      nodePort: 30084
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: marketing-service-nodeport
  namespace: crm
spec:
  selector:
    app: marketing-service
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30085
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: communication-service-nodeport
  namespace: crm
spec:
  selector:
    app: communication-service
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30086
  type: NodePort
